### ISSUE TITLE
Race condition when updating the ARI modules index

### ISSUE THREAD

**Issue by mbwhite** [ansible/ansible-risk-insight#146]
_Observed_ 
Issue was that when updating an existing ARI knowledge base, some of the new collections had findings added, but are absent from the modules index. 

The effect is that on lookups, the module is reported as not existing; when in fact it does.

_Possible Cause_

Updates to the `module_index.json` appears to be done at the scanner level, so if multiple of these are running parallel is there a potential race condition? The multiple run is the standard way of working; with over 300 modules in the current set I need to use running in parallel is important.

**Comment by mbwhite** [comment]
I've done some testing post PR #150 being added.. thanks @yuji-watanabe-jp @hirokuni-kitahara 

However, when recreating the ARI index I'm still seeing cases where the index is missing modules that have been scanned successfully.  Whilst the file locking I think has helped - suspect it has only helped as far as slowing the code so the problem below is not as frequent.  

The code that updates the module index is [here](https://github.com/ansible/ansible-risk-insight/blob/58ba8b489c28a2da91dab5c8d7ef51693d63f29f/ansible_risk_insight/risk_assessment_model.py#L141)
It loads the index file, then processes the data, and saves the file with anything updated.
This function is being run concurrently - whilst the read/write files are locked - I think there's a chance that between the file being read, updated and then written out, the file has been updated elsewhere, hence the information could be lost

**Comment by hirokuni-kitahara** [comment]
Hi @mbwhite, thank you for testing the latest changes!
I think the reason you are seeing some missing modules in the index is simply the number of the contents in the KB data we are using right now.
The current KB data contains top 100 collections & top 100 roles based on download count, and other collections/roles are not included.
Actually `kubernetes.core` was included in the list but `community.kubernetes` was not.
We are working on extending this to all the collections/roles.

**Comment by hirokuni-kitahara** [comment]
let me close this for now since the issue itself is resolved.
