### ISSUE TITLE
Modules with rename / redirected history reported as not existing

### ISSUE THREAD

**Issue by mbwhite** [ansible/ansible-risk-insight#152]
Some modules that have a history of rename, are causing issues when trying to search for them. There are a number of concern; but as an example

if you look for `community.kubernetes.k8s` ARI will return the module does not exist. However looking in the indexes file, we can see it does, but the fqcn has changed.  This make sit hard to search for. 

```
   "k8s": [
        {
            "fqcn": "kubernetes.core.k8s",
            "type": "collection",
            "name": "kubernetes.core",
            "version": "2.4.0",
            "hash": "3713580886f8f9b509f5ce09cee360675ce45b170e53631d9307b76d1dcdbf2c"
        },
        {
            "fqcn": "kubernetes.core.k8s",
            "type": "collection",
            "name": "community.kubernetes",
            "version": "2.0.1",
            "hash": "ca9f014c93d6198a10afa93987e7de4a599e71897b7488fb7c5609e489211494"
        },
        {
            "fqcn": "community.okd.k8s",
            "type": "collection",
            "name": "community.okd",
            "version": "2.3.0",
            "hash": "9b5eb97135d64f063d2a021686336abbd5d798c9e57e4f8c1198cc66e79e4f99"
        },
        {
            "fqcn": "shanemcd.kubernetes.k8s",
            "type": "collection",
            "name": "shanemcd.kubernetes",
            "version": "0.11.0",
            "hash": "d9068b33c4d78c6dae57ba10607820ce0b3765a9d6c89b6fa87c9bd5c73772a7"
        }
    ],
```

The first 20 or so that appear to be representative of the whole

      "community.aws.ec2_asg_scheduled_action",
      "community.crypto.openssl_certificate",
      "community.elastic.elastic_bulk",
      "community.elastic.elastic_role",
      "community.elastic.elastic_snapshot",
      "community.elastic.elastic_user",
      "community.general.hana_query",
      "community.general.sap_task_list_execute",
      "community.general.sapcar_extract",
      "community.kubernetes.helm",
      "community.kubernetes.helm_repository",
      "community.kubernetes.k8s",
      "community.kubernetes.k8s_exec",
      "community.kubernetes.k8s_info",
      "consoledot.edgemanagement.custom_repositories",
      "consoledot.edgemanagement.groups",
      "dellemc.openmanage.idrac_firmware",
      "dellemc.openmanage.idrac_server_config_profile",
      "dellemc.openmanage.ome_device_info",
      "ibm.cloud.ibm_iam_access_group",
      "ibm.cloud.ibm_resource_group",
      "infoblox.nios_modules.nios_a_record",
      "infoblox.nios_modules.nios_cname_record",
      "infoblox.nios_modules.nios_dns_view",
      "infoblox.nios_modules.nios_host_record",
      "infoblox.nios_modules.nios_member",
      "infoblox.nios_modules.nios_mx_record",
      "infoblox.nios_modules.nios_naptr_record",
      "infoblox.nios_modules.nios_network_view",
      "infoblox.nios_modules.nios_nsgroup",
      "infoblox.nios_modules.nios_ptr_record",
      "infoblox.nios_modules.nios_srv_record",
      "infoblox.nios_modules.nios_txt_record",
      "infoblox.nios_modules.nios_zone",
      "servicenow.itsm.attachment"

**Comment by hirokuni-kitahara** [comment]
The latest version of ARI will add `deprecated` flag to module index data, and it can be used to judge if the index is module redirect or actual module exists in a collection.
Let me close this issue now.
