### ISSUE TITLE
Missing command line option for scanning all of the taskfiles in a repo when scanning is done using project option

### ISSUE THREAD

**Issue by justjais** [ansible/ansible-risk-insight#221]
Missing command line option for scanning all of the taskfiles in a repo when scanning is done using `project` option.

- For scanning each of the task files via `project` level scanning, ARI should make `load_all_taskfiles=True` which is currently missing. Once updated project level scanning would run ARI scanning for each of the valid playbook from the input repo.

**Comment by justjais** [comment]
cc. @hirokuni-kitahara

**Comment by hirokuni-kitahara** [comment]
Let me close this issue because it is already implemented. Thank you.
