### ISSUE TITLE
Better system structure between ARI components

### ISSUE THREAD

**Issue by yuji-watanabe-jp** [ansible/ansible-risk-insight#32]
### Define interfaces and parameters

- [x] support multiple input patterns
- [ ] refine ARI findings data format
- [ ] document all command for ARI
- [ ] document all in/out

### Data storage for intermediates and outputs
- [x] Dep Preparator実装
- [x] RAM 
- [ ] RAM Generator
- [ ] Prepare RAM for Galaxy using RAM Generator
- [ ] Support search path for Ansible

**Comment by hirokuni-kitahara** [comment]
Let me close this issue because the main items are already implemented.
